# Generated by Django 5.0.1 on 2024-02-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
